version: '3.8'

services:
  formfillapi:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile
    container_name: formfillapi
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      # 持久化模板和输出文件
      - ./data/templates:/app/templates
      - ./data/output:/app/output
      - ./data/logs:/app/logs
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xms1g -Xmx2g -XX:+UseG1GC
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - formfillapi-network

  nginx:
    image: nginx:alpine
    container_name: formfillapi-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - formfillapi
    networks:
      - formfillapi-network

networks:
  formfillapi-network:
    driver: bridge

volumes:
  templates:
  output:
  logs: 