server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: FormFillAPI
  
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
  
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  # 邮件配置
  mail:
    # 默认为QQ邮箱，可根据需要修改
    #host: smtp.qq.com
    host: smtp.126.com
    port: 25
    username: xingyun1982314@126.com
    password: EUgES6xakxi4g8km # 使用QQ邮箱的授权码
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        debug: false
    protocol: smtp
    default-encoding: UTF-8

# 邮件发送配置
email:
  # 可配置的邮件内容模板
  template:
    subject: "${formName} - 表单处理完成通知 - ${timestamp}"
    content: |
      尊敬的用户，您好！
      
      您提交的表单 "${formName}" 已经处理完成。
      
      表单状态：${formStatus}
      处理时间：${timestamp}
      
      请查看附件中的处理结果。
      
      如有任何问题，请联系系统管理员。
      
      此邮件为系统自动发送，请勿回复。
      
      谢谢！
  # 收件人邮箱列表
  recipients:
    - "xingyun1982314@126.com"
    - "xingyun1982314@126.com"
  # 发件人显示名称
  from-name: "表单处理系统"

logging:
  level:
    com.formfill.api: INFO
    org.apache.poi: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/formfill-api.log
    
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always 